### PR TITLE
Replace all "colour" by "color"

### PR DESCRIPTION
**Pull request by raed667**
Signed-off-by: Raed CHAMMAM <raed.chammam@gmail.com>

### CODE REVIEW

**Comment by raed667** [comment]
Just for the lulz :trollface:

**Comment by derhuerst** [comment]
LGTM 😛

**Comment by derhuerst** [comment]
@juliuste ping! fix this ASAP

**Comment by juliuste** [comment]
Lol 😄 Nice try :trollface:, but I'm afraid I can't let you do that 😛

**Pull request closed without merging**
