### PR TITLE
tests added

### PR DESCRIPTION
**Pull request by grigori-gru**
Maybe I don't catch what kind of tests you needed. But I tried to convert svg to JSON, it makes easier to see diffs into comparing data.

### CODE REVIEW

**Comment by juliuste** [comment]
Thank you very much, why do you store the data as an HTML file though? 😄 Couldn't you just store it as SVG? And please move the additional dependencies added by you to the `dev-dependencies` since they are not required by the main module 🙂 (Maybe see also juliuste/parliament-svg#7)

**Comment by grigori-gru** [comment]
Hello! I update my tests.
Hope it helps you.

**Comment by juliuste** [comment]
Thank you very much 🙂

**Comment by juliuste** [comment]
Fixes #1

**Pull request merged**
